apiVersion: v1
kind: ReplicaSet
metadata:
  name: webfrontend
  labels:
    app: webfrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webfrontend
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
        - name: webfrontend
          image: httpd:latest
          ports:
            - containerPort: 80
